-- Migration file: supabase/migrations/20260306000001_create_tech_tools_table.sql

-- ==========================================
-- 1. BUAT TABEL TECH TOOLS
-- ==========================================
CREATE TABLE IF NOT EXISTS public.tech_tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    "iconKey" TEXT NOT NULL,
    "iconColor" TEXT NOT NULL,
    description TEXT NOT NULL,
    "usageRating" SMALLINT NOT NULL,
    badge TEXT NOT NULL,
    "isFavorite" BOOLEAN NOT NULL DEFAULT false,
    "officialUrl" TEXT NOT NULL,
    tags TEXT[] NOT NULL DEFAULT '{}',
    detail TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Mengaktifkan Row Level Security (RLS)
ALTER TABLE public.tech_tools ENABLE ROW LEVEL SECURITY;

-- Hapus policy lama jika ada, lalu buat baru (Idempotent)
DROP POLICY IF EXISTS "Allow public read access to tech_tools" ON public.tech_tools;
CREATE POLICY "Allow public read access to tech_tools"
ON public.tech_tools FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow authenticated full access to tech_tools" ON public.tech_tools;
CREATE POLICY "Allow authenticated full access to tech_tools"
ON public.tech_tools FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);