-- Migration file: supabase/migrations/20260306000000_create_timelines_table_and_bucket.sql

-- ==========================================
-- 1. BUAT TABEL TIMELINES
-- ==========================================
CREATE TABLE IF NOT EXISTS public.timelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    subtitle TEXT,
    location TEXT NOT NULL,
    "locationDetail" TEXT,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    status TEXT NOT NULL,
    description TEXT NOT NULL,
    gpa TEXT,
    extracurricular TEXT[],
    responsibilities TEXT[],
    projects TEXT[],
    certificates JSONB DEFAULT '[]'::jsonb,
    "awardLevel" TEXT,
    highlights TEXT[] NOT NULL DEFAULT '{}',
    skills TEXT[] NOT NULL DEFAULT '{}',
    photos JSONB NOT NULL DEFAULT '[]'::jsonb,
    quote TEXT,
    quote_author TEXT,
    color TEXT NOT NULL,
    icon TEXT NOT NULL,
    "techStack" TEXT[],
    "externalLink" JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.timelines ENABLE ROW LEVEL SECURITY;

-- Hapus policy lama jika ada, lalu buat baru (Idempotent)
DROP POLICY IF EXISTS "Allow public read access to timelines" ON public.timelines;
CREATE POLICY "Allow public read access to timelines"
ON public.timelines FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow authenticated full access to timelines" ON public.timelines;
CREATE POLICY "Allow authenticated full access to timelines"
ON public.timelines FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- ==========================================
-- 2. BUAT STORAGE BUCKET UNTUK TIMELINE
-- ==========================================
-- Menambahkan bucket 'timeline' jika belum ada
INSERT INTO storage.buckets (id, name, public)
VALUES ('timeline', 'timeline', true)
ON CONFLICT (id) DO NOTHING;

-- Hapus policy storage lama jika ada, lalu buat baru (Idempotent)
DROP POLICY IF EXISTS "Public Access to Timeline Images" ON storage.objects;
CREATE POLICY "Public Access to Timeline Images"
ON storage.objects FOR SELECT
USING (bucket_id = 'timeline');

DROP POLICY IF EXISTS "Auth Users Manage Timeline Images" ON storage.objects;
CREATE POLICY "Auth Users Manage Timeline Images"
ON storage.objects FOR ALL
TO authenticated
USING (bucket_id = 'timeline')
WITH CHECK (bucket_id = 'timeline');